language: python
python:
  - "2.7"

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "profk567-github"
    token: $SONAR_TOKEN

# command to run tests
script:
  - python -m unittest TestTriangle
  - sonar-scanner
