language: python
python:
  - "2.7"

dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "sonarsource"
    token: "EsH9ZY/JRiq6o/oinj5Mi+6i0UwjSnViJ50BNyWEPzl9+jDK5+ihpgx73IA7MtwraJvy3qCjU1zfu4mEmB4PNbu5e1uVsbQzEbAKASyxQ6IMLu2rgZ/5dmGhYzvO7VsQj2Y7/4Cof3/3btka2RYlyiiCHLZsipPL9Jqpd9sI50QJ/qNwC0ssa86d+/ec070Ho8ia3e7flDDUZN+xpI+jGeFLBwPUZh0pY+NPJbH9rd+4xIK82cXwvz3p1wNTI3i9LEP9F1Ww+QdYULAly5wRlkxbqFFNwWHLwqjKlFVZ8bVdiIdJaGcGaPtbzvWdtk+iqunZBrrEqT7HX2yDDSsUdJu//PmGDQ6hhefFWZ8tEwd2NPNol5BAmhVEd/B3Lej0W2XhJs+400VF0I43ukBf+sTXKnYMlaUEQJRF/FIAiV2Axb99K7laxYRl5q86HcDnepF9Lk41mAMFvx+P4zYvbGPH/hTMQNInJwZg5tWa+pEdAwBziTDV4IOe9vct4f+3KvQ/G75ZnfuSR0FJp1FM7c4moS1bsBR9J1ZV0lrAR5+i5cwwtLUhwjxXxILr6v8zAlzBbnicorEg572kjQCCq21eeEOwF901I05TwPsTzrenw8lB7994j7gvBvKQKv5jDIIbogTYdXBaiU77ChxYtEhhYQXChfC0/LMBCtpcyVg="

# command to run tests
script:
  - python -m unittest TestTriangle
  - sonar-scanner
